#!/usr/bin/env python

import sys

from rqt_mypkg.my_module import MyPlugin
from rqt_gui.main import Main

plugin = 'rqt_mypkg.my_module.MyPlugin'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))